# Generated by Django 2.0.5 on 2018-05-31 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_place_restaurant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('place_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='news.Place')),
                ('customers', models.ManyToManyField(related_name='provider', to='news.Place')),
            ],
            bases=('news.place',),
        ),
    ]
