# Generated by Django 2.0.5 on 2018-05-31 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_supplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProxyPlace',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('news.place',),
        ),
    ]
