# Generated by Django 2.0.5 on 2018-05-31 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_proxyplace'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProxyPlace',
        ),
    ]
